version: '3.8'

services:
  # Backend - Flask with hot reload
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # 소스코드 마운트 (핫 리로드)
      - /app/venv  # venv는 제외
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - AWS_PROFILE=${AWS_PROFILE}
      - BEDROCK_REGION=ap-northeast-2
      - DYNAMODB_VECTORS_TABLE=dev-beacon-vectors
      - CHROMA_DATA_DIR=/app/chroma_data
    networks:
      - beacon-network
    command: python app.py  # Flask 개발 서버 실행

  # Frontend - React dev server with hot reload  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # 소스코드 마운트 (핫 리로드)
      - /app/node_modules  # node_modules는 제외
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true  # Docker에서 파일 변경 감지
      - WATCHPACK_POLLING=true
    networks:
      - beacon-network
    command: npm start  # React 개발 서버 실행

networks:
  beacon-network:
    driver: bridge